### ISSUE TITLE
Concurrent Modification Exception on Android 10

### ISSUE THREAD

**Issue by duocnguyen6799** [parse-community/ParseLiveQuery-Android#117]
I used ParseLiveQuery SDK on version 1.1.0 and 1.2.2 . My app has been crashed like below.
![image](https://user-images.githubusercontent.com/41044684/103396675-1b7fb100-4b67-11eb-926d-8980dfac6952.png)
Please help me! Thanks.

**Comment by mmimeault** [comment]
Hello, could you please provide more information?

Stacktrace?
SDK version?
How to reproduce?

On my side, we are using the latest version intensively or many devices and we don't have that error.

Thanks

**Comment by duocnguyen6799** [comment]
I have just updated the information on this issue.

**Comment by duocnguyen6799** [comment]
> Hello, could you please provide more information?
> 
> Stacktrace?
> SDK version?
> How to reproduce?
> 
> On my side, we are using the latest version intensively or many devices and we don't have that error.
> 
> Thanks

**Comment by mmimeault** [comment]
@duocnguyen6799 Issue is fixed now?

**Comment by phamthuy1998** [comment]
Still has the same issue on version 1.2.2

> @duocnguyen6799 Issue is fixed now?

**Comment by mmimeault** [comment]
Does make sense. The `mCallbacks` list is not thread safe.
Just realized I don't have this stack trace because I don't use `registerListener` nor `unregisterListener`.

Easy fix could be 

- to add `synchronized`, 
- or use a thread-safe version of the Array list (Collections.synchronizedList or CopyOnWriteArrayList) 
- or any other better suggestion.

**Comment by phamthuy1998** [comment]
Let me try. Thanks for help
