### ISSUE TITLE
SubscriptionHandling thread

### ISSUE THREAD

**Issue by ghost** [parse-community/ParseLiveQuery-Android#47]
thanks for your ParseLiveQuery implementation. 
is SubscriptionHandling running in the main tread or background thread?

**Comment by jhansche** [comment]
The SubscriptionHandling callbacks will happen on a background thread.  You will need to post back to a main thread Handler in order to make updates to the UI.

I have a subscription handling callback that automatically queued up and dispatches events to the main thread.  I'll work on porting that over to this library so it can be used optionally in place of having to do that work yourself.
